### ISSUE TITLE
Installing module from github fails

### ISSUE THREAD

**Issue by pattieja1** [atrodo/App-MechaCPAN#15]
mechacpan install --verbose https://github.com/spiritloose/mod_psgi.git

Spits out

```
Resolving     https://github.com/spiritloose/mod_psgi.git
git	--version
git	clone	--bare	https://github.com/spiritloose/mod_psgi.git	/root/perl/local/tmp/mecha_mod_psgi.git.20181110_175956.4cEX
Cloning into bare repository '/root/perl/local/tmp/mecha_mod_psgi.git.20181110_175956.4cEX'...
git	archive	--format=tar.gz	--remote=/root/perl/local/tmp/mecha_mod_psgi.git.20181110_175956.4cEX	master
```
and a bunch of binary garbage and exits with

```
Error         Could not install https://github.com/spiritloose/mod_psgi.git

Installed 0 modules

Failed to install 1 modules 
```

I have tried this in the docker builds against centos 7 and a native debian wheezy box.   Perl 5.26.3 with the same output.

**Comment by atrodo** [comment]
That project doesn't appear to be a perl distribution that can be installed with a CPAN installer, it doesn't have a Makefile.PL nor a Build.PL. And actually the repository doesn't include the actual configure script, only the configure.ac ready for autotools. So as it stands, MechaCPAN cannot install this repository. 

What I am suprised by and will investigate, is the fact that it didn't tell you it couldn't find Makefile.PL nor Build.PL. Also, --verbose should not dump the binary data to the screen. That is the binary of the tar.gz archive of the repository and putting it on the screen is useless and confusing.

**Comment by atrodo** [comment]
I just pushed a couple commits to master that deals with both parts of this. First (909e4cc8) fixes a bug that installing git repositories were not working because the argument to inflate_archive was a File::Temp object and it was doing a -e test on it. Stringifing it fixed the issue. The second (058af62a) fixes the dumping of binary data to the screen. I threw in a better error about the missing Makefile.PL/Build.PL as well. That should help you out with that bug, even if mechacpan can't install the requested module.

**Comment by pattieja1** [comment]
I just updated my master branch and tried to run your tests on a native Debian Wheezy install.  Things failed.  :(

I'm including all the commands I ran and their output.

```root@james:~/perl/App-MechaCPAN# git co master
Switched to branch 'master'
Your branch is behind 'origin/master' by 10 commits, and can be fast-forwarded.
root@james:~/perl/App-MechaCPAN# git pull
remote: Enumerating objects: 103, done.
remote: Counting objects: 100% (103/103), done.
remote: Compressing objects: 100% (11/11), done.
remote: Total 174 (delta 88), reused 102 (delta 88), pack-reused 71
Receiving objects: 100% (174/174), 47.96 KiB, done.
Resolving deltas: 100% (90/90), completed with 26 local objects.
From https://github.com/atrodo/App-MechaCPAN
   00f111a..80b2fa5  master     -> origin/master
From https://github.com/atrodo/App-MechaCPAN
 * [new tag]         0.24       -> 0.24
 * [new tag]         0.25       -> 0.25
 * [new tag]         0.26       -> 0.26
Updating 69fdca9..80b2fa5
Fast-forward
 Changes                                         |   27 ++++++++++
 META.json                                       |   10 ++--
 Makefile.PL                                     |    4 +-
 README.md                                       |    6 +--
 lib/App/MechaCPAN.pm                            |  458 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++--------------------
 lib/App/MechaCPAN/Deploy.pm                     |    7 +--
 lib/App/MechaCPAN/Install.pm                    |   67 ++++++++++-------------
 lib/App/MechaCPAN/Perl.pm                       |   50 +++++++++--------
 t/04_opts.t                                     |   25 +++++++--
 t/06_restart.t                                  |  153 ++++++++++++++++++++++++++++++++++++++++++++++++++++
 t/07_tmpdata.t                                  |  126 +++++++++++++++++++++++++++++++++++++++++++
 t/11_perl.t                                     |   15 +++++-
 t/22_install__get_targz.t                       |    2 +-
 t/23_install_array.t                            |    3 ++
 t/25_depend_source.t                            |    9 +++-
 t/26_keep_processing.t                          |    2 +
 t/26_subseq_prereq.t                            |    2 +-
 t/27_opts.t                                     |    2 +
 t/35_deploy_snapshot.t                          |    9 +++-
 test_dists/CoreDeprDeps/CoreDeprDeps-1.0.tar.gz |  Bin 0 -> 7988 bytes
 test_dists/CoreDeprDeps/cpanfile                |    3 ++
 test_dists/CoreDeprDeps/dist.ini                |    7 +++
 test_dists/CoreDeprDeps/lib/CoreDeprDeps.pm     |    9 ++++
 test_dists/CoreDeprDeps/t/basic.t               |   13 +++++
 test_dists/FakePerl-5.12.0.tar.gz               |  Bin 20480 -> 538 bytes
 zhuli.PL                                        |   16 +++++-
 26 files changed, 884 insertions(+), 141 deletions(-)
 create mode 100644 t/06_restart.t
 create mode 100644 t/07_tmpdata.t
 create mode 100644 test_dists/CoreDeprDeps/CoreDeprDeps-1.0.tar.gz
 create mode 100644 test_dists/CoreDeprDeps/cpanfile
 create mode 100644 test_dists/CoreDeprDeps/dist.ini
 create mode 100644 test_dists/CoreDeprDeps/lib/CoreDeprDeps.pm
 create mode 100644 test_dists/CoreDeprDeps/t/basic.t
root@james:~/perl/App-MechaCPAN# perl Makefile.PL 
Generating a Unix-style Makefile
Writing Makefile for App::MechaCPAN
Writing MYMETA.yml and MYMETA.json
root@james:~/perl/App-MechaCPAN# make test
cp lib/App/MechaCPAN.pm blib/lib/App/MechaCPAN.pm
cp lib/App/MechaCPAN/Perl.pm blib/lib/App/MechaCPAN/Perl.pm
cp lib/App/MechaCPAN/Install.pm blib/lib/App/MechaCPAN/Install.pm
cp lib/App/MechaCPAN/Deploy.pm blib/lib/App/MechaCPAN/Deploy.pm
"/usr/bin/perl" "-Iblib/arch" "-Iblib/lib" zhuli.PL zhuli
Will include 'MechaCPAN.pm' in 'zhuli'
Will include 'Deploy.pm' in 'zhuli'
Will include 'Install.pm' in 'zhuli'
Will include 'Perl.pm' in 'zhuli'
cp script/mechacpan blib/script/mechacpan
"/usr/bin/perl" -MExtUtils::MY -e 'MY->fixin(shift)' -- blib/script/mechacpan
PERL_DL_NONLAZY=1 "/usr/bin/perl" "-MExtUtils::Command::MM" "-MTest::Harness" "-e" "undef *Test::Harness::Switches; test_harness(0, 'blib/lib', 'blib/arch')" t/*.t
t/01_sanity.t .............. 1/? 
t/01_sanity.t .............. ok   
t/02_cmds.t ................ ok   
t/03_run.t ................. ok   
t/04_opts.t ................ ok   
t/05_re.t .................. ok    
t/06_restart.t ............. 
t/06_restart.t ............. ok    
t/07_tmpdata.t ............. ok    
t/11_perl.t ................ # logging to 'local/logs/mecha_log.20190317_084346.E_6m'...
# Looks like /root/perl/App-MechaCPAN/t/../test_dists/FakePerl-5.12.0.tar.gz is perl 5.12.0, assuming that's true
# Fetching perl 5.12.0
# Configuring perl 5.12.0
# Building perl 5.12.0
# Testing perl 5.12.0
# Installing perl 5.12.0
# Installed perl 5.12.0
t/11_perl.t ................ ok   
t/12_perl__get_targz.t ..... ok   
t/13_perl_smart_tests.t .... ok   
t/14_perl_opts.t ........... ok    
t/21_install.t ............. ok    
t/22_install__get_targz.t .. 5/? 
#   Failed test 'Got 'https://github.com/p5sagit/Try-Tiny.git''
#   at t/22_install__get_targz.t line 49.
t/22_install__get_targz.t .. 6/? 
#   Failed test 'Got 'https://github.com/p5sagit/Try-Tiny.git@v0.24''
#   at t/22_install__get_targz.t line 49.
t/22_install__get_targz.t .. 12/? # Looks like you failed 2 tests of 14.
t/22_install__get_targz.t .. Dubious, test returned 2 (wstat 512, 0x200)
Failed 2/14 subtests 
t/23_install_array.t ....... ok   
t/24_simple_source.t ....... ok   
t/25_depend_source.t ....... # (BEGIN) Try::Tiny => 
# cwd => /tmp/PrCPPFGFLB
# Try::Tiny => 
t/25_depend_source.t ....... 1/? # Try::Tiny => 
# Try::Tiny => 
# Try::Tiny => 
t/25_depend_source.t ....... ok   
t/26_avoid_reinstall.t ..... ok   
t/26_keep_processing.t ..... #  - Failed to install 1 modules
t/26_keep_processing.t ..... 1/? #  - Failed to install 1 modules
t/26_keep_processing.t ..... ok   
t/26_subseq_prereq.t ....... ok   
t/27_opts.t ................ #  - Failed to install 1 modules
t/27_opts.t ................ 5/? #  - Failed to install 1 modules
t/27_opts.t ................ 7/? #  - Failed to install 1 modules
t/27_opts.t ................ 8/? #  - Failed to install 1 modules
t/27_opts.t ................ 10/? #  - Failed to install 1 modules
t/27_opts.t ................ ok    
t/31_cpanfile.t ............ ok   
t/32_deploy.t .............. ok   
t/33_snapshot.t ............ ok   
t/34_deploy_correct.t ...... ok   
t/35_deploy_snapshot.t ..... ok   
t/gh3.t .................... 3/? #  - Failed to install 1 modules
#  - Failed to install 1 modules
t/gh3.t .................... ok   
t/gh6_git_min_ver.t ........ ok   

Test Summary Report
-------------------
t/22_install__get_targz.t (Wstat: 512 Tests: 14 Failed: 2)
  Failed tests:  5-6
  Non-zero exit status: 2
Files=27, Tests=234, 150 wallclock secs ( 0.10 usr  0.03 sys + 61.68 cusr  8.00 csys = 69.81 CPU)
Result: FAIL
Failed 1/27 test programs. 2/234 subtests failed.
make: *** [test_dynamic] Error 255
root@james:~/perl/App-MechaCPAN# which perl
/usr/bin/perl
root@james:~/perl/App-MechaCPAN# perl -v

This is perl 5, version 14, subversion 2 (v5.14.2) built for x86_64-linux-gnu-thread-multi
(with 105 registered patches, see perl -V for more detail)

Copyright 1987-2011, Larry Wall

Perl may be copied only under the terms of either the Artistic License or the
GNU General Public License, which may be found in the Perl 5 source kit.

Complete documentation for Perl, including FAQ lists, should be found on
this system using "man perl" or "perldoc perl".  If you have access to the
Internet, point your browser at http://www.perl.org/, the Perl Home Page.
```

**Comment by atrodo** [comment]
I've pushed another change that should fixes the issue as well as not break other tests. It also added tests, so I'm more confident that I made the correct fix this time.

**Comment by pattieja1** [comment]
make test passes with latest changes in master. :)

**Comment by pattieja1** [comment]
It's still spitting out the garbage (but only in --verbose mode), so unless I'm not running your latest changes perl 5.14.2 on Debian Wheezy isn't happy.

**Comment by pattieja1** [comment]
On a separate note, the date used in the log filename is off by a month.  It's showing 20190415 instead of 20190515 for todays date.

**Comment by atrodo** [comment]
I hadn't even noticed the off-by-one in the date, I've fixed that. But the garbage in the output I'm unable to replicate. although I'm not running Wheezy, I am running with 5.14 and when I checkout 0.26 I get the garbage. When I update to master I no longer get garbage. You might want to try a ```which mechacpan``` or ```type mechacpan``` to make sure it's picking up the new version instead of a cpan version.

**Comment by pattieja1** [comment]
I just updated my master checkout, did:

make clean
perl Makefile.PL
make test (everything passed)
make uninstall (manually removed files listed)
make install

```
Manifying 4 pod documents
Installing /usr/local/share/perl/5.14.2/App/MechaCPAN.pm
Installing /usr/local/share/perl/5.14.2/App/MechaCPAN/Deploy.pm
Installing /usr/local/share/perl/5.14.2/App/MechaCPAN/Install.pm
Installing /usr/local/share/perl/5.14.2/App/MechaCPAN/Perl.pm
Installing /usr/local/man/man3/App::MechaCPAN.3pm
Installing /usr/local/man/man3/App::MechaCPAN::Perl.3pm
Installing /usr/local/man/man3/App::MechaCPAN::Deploy.3pm
Installing /usr/local/man/man3/App::MechaCPAN::Install.3pm
Installing /usr/local/bin/mechacpan
Appending installation info to /usr/lib/perl/5.14/perllocal.pod
```

cd to directory with local dir to work with
which mechacpan (verified it's the one just installed)

mechacpan install --verbose https://github.com/spiritloose/mod_psgi.git

Date format is still showing 20190416 and I'm still getting the gzip garbage in output.

```
Restarting to local perl 
/root/perl/local/perl/bin/perl /usr/local/bin/mechacpan install --verbose https://github.com/spiritloose/mod_psgi.git


logging to '/root/perl/local/logs/mecha_log.20190416_125225.WcqY'... 

Resolving     https://github.com/spiritloose/mod_psgi.git
git	--version
git	clone	--bare	https://github.com/spiritloose/mod_psgi.git	/root/perl/local/tmp/mecha_mod_psgi.git.20190416_125225.U6oR
Cloning into bare repository '/root/perl/local/tmp/mecha_mod_psgi.git.20190416_125225.U6oR'...
git	archive	--format=tar.gz	--remote=/root/perl/local/tmp/mecha_mod_psgi.git.20190416_125225.U6oR	master

garbage ensues

Error         Could not install https://github.com/spiritloose/mod_psgi.git

Installed 0 modules

Failed to install 1 modules 

```

**Comment by atrodo** [comment]
So I've tried a couple times but am unable to replicate. I've detailed all the commands I ran below to try and reproduce your steps as best as I could, including a fresh copy from master. 
```
{atrodo@zUzZoqpi2O}> git clone https://github.com/atrodo/App-MechaCPAN.git
Cloning into 'App-MechaCPAN'...
remote: Enumerating objects: 36, done.
remote: Counting objects: 100% (36/36), done.
remote: Compressing objects: 100% (20/20), done.
remote: Total 1882 (delta 10), reused 32 (delta 10), pack-reused 1846
Receiving objects: 100% (1882/1882), 489.23 KiB | 0 bytes/s, done.
Resolving deltas: 100% (866/866), done.
Checking connectivity... done.
{atrodo@App-MechaCPAN}> perl Makefile.PL
Writing Makefile for App::MechaCPAN
Writing MYMETA.yml
{atrodo@App-MechaCPAN}> make test
```
(Skip a lot of output, the tests on 5.14 are very verbose for unrelated reasons)
```
All tests successful.
Files=27, Tests=241, 71 wallclock secs ( 0.12 usr  0.06 sys + 40.52 cusr  8.26 csys = 48.96 CPU)
Result: PASS
{atrodo@App-MechaCPAN}> make install
Manifying blib/man3/App::MechaCPAN.3
Manifying blib/man3/App::MechaCPAN::Perl.3
Manifying blib/man3/App::MechaCPAN::Install.3
Manifying blib/man3/App::MechaCPAN::Deploy.3
/home/atrodo/.plenv/versions/5.14.4/bin/perl5.14.4 "-Iblib/arch" "-Iblib/lib" zhuli.PL zhuli
Will include 'MechaCPAN.pm' in 'zhuli'
Will include 'Perl.pm' in 'zhuli'
Will include 'Install.pm' in 'zhuli'
Will include 'Deploy.pm' in 'zhuli'
Installing /home/atrodo/.plenv/versions/5.14.4/lib/perl5/site_perl/5.14.4/App/MechaCPAN.pm
Installing /home/atrodo/.plenv/versions/5.14.4/lib/perl5/site_perl/5.14.4/App/MechaCPAN/Perl.pm
Installing /home/atrodo/.plenv/versions/5.14.4/lib/perl5/site_perl/5.14.4/App/MechaCPAN/Install.pm
Installing /home/atrodo/.plenv/versions/5.14.4/lib/perl5/site_perl/5.14.4/App/MechaCPAN/Deploy.pm
Installing /home/atrodo/.plenv/versions/5.14.4/man/man3/App::MechaCPAN::Install.3
Installing /home/atrodo/.plenv/versions/5.14.4/man/man3/App::MechaCPAN::Perl.3
Installing /home/atrodo/.plenv/versions/5.14.4/man/man3/App::MechaCPAN::Deploy.3
Installing /home/atrodo/.plenv/versions/5.14.4/man/man3/App::MechaCPAN.3
Installing /home/atrodo/.plenv/versions/5.14.4/bin/mechacpan
Appending installation info to /home/atrodo/.plenv/versions/5.14.4/lib/perl5/5.14.4/x86_64-linux/perllocal.pod
```
Since it is installed into a plenv directory, I reference it by full path
```
{atrodo@zUzZoqpi2O}> /home/atrodo/.plenv/versions/5.14.4/bin/mechacpan install --verbose https://github.com/spiritloose/mod_psgi.git


logging to 'local/logs/mecha_log.20190609_233917.f429'...

Resolving     https://github.com/spiritloose/mod_psgi.git
git     --version
git     clone   --bare  https://github.com/spiritloose/mod_psgi.git     /tmp/gbG23brZVg
Cloning into bare repository '/tmp/gbG23brZVg'...
git     archive --format=tar.gz --remote=/tmp/gbG23brZVg        master
Configuring   https://github.com/spiritloose/mod_psgi.git
Configuring   https://github.com/spiritloose/mod_psgi.git
Configuring   https://github.com/spiritloose/mod_psgi.git
Error         Could not install https://github.com/spiritloose/mod_psgi.git

Installed 0 modules

Failed to install 1 modules

{atrodo@zUzZoqpi2O}>
```

I suspect you're still pulling from commit 80b2fa5 or even older. The output of ```git log | head -1``` should read as:
```
commit 4857a571c62ce13b683aee34bb687619dee7f4b1
```

If that is the commit that you're seeing, then I'm not sure where to go. The date change fix and garbage removal are gone for me on that commit so you should no longer be seeing either.

**Comment by pattieja1** [comment]
I confirmed I'm on the same git commit as you listed.

I think the problem is because the version of App::MechaCPAN installed into the local directory is not getting updated and so when mechacpan is called, it is using that version instead of the system installed version and so the problems are still seen.

I apparently didn't re-create the local install on this latest test.  Doing that now.

**Comment by pattieja1** [comment]
re-creating local fixed the problem.

I'll have to remember that for future tests. :)

**Comment by atrodo** [comment]
Oh, I think I understand now. Let me try and get this straight:

You installed mechacpan into system perl
PERL5LIB is set to ```/<something>/local/lib/```
Running ```mechcpan``` therefore caused it to load the version in ```/<something>/local/lib/```
Problem ensued.

That makes sense. I'll noodle on it a little bit, but I'm not sure there is much I can do for that. Maybe I can force the script to detect that and break using module versions.

**Comment by pattieja1** [comment]
correct.  Because the `mechacpan perl` step installs the App::MechaCPAN module into the newly built `local/lib`, so that `mechacpan install` works when it relaunches using the perl from `local`.  I was just updating the system perl's version of App::MechaCPAN and not re-installing it into `local`.  I totally forgot about it being in `local`.

Maybe we have the code check for if the running module is going to be a different file than in the `local/lib`, then it compares versions and if they don't match it throws a warning and quits, so that the user can get `local` into sync with the current App::MechaCPAN?

**Comment by pattieja1** [comment]
To clarify, the version of perl initially running `mechacpan` is `/usr/bin/perl` and not `~/local/bin/perl`, thus `mechacpan install` was re-launching with the `local/bin/perl` version and running the older App::MechaCPAN code base. :(
